name: "Create additional tags"

on:
  release:
    types: ["released"]

jobs:
  create-additional-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
